### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [rlguy/GridFluidSim3D#10]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/rlguy/GridFluidSim3D/blob/b872ef29c5e0d7132c80871f9ff620976b9ec695/Makefile#L1) so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/)
- [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction)

**Comment by rlguy** [comment]
Hello elfring,

Thanks for the suggestion! I will be looking into how to use CMake to create a higher level build system.

Best Regards,
Ryan

**Comment by rlguy** [comment]
Hello elfring,

I have updated the project to use CMake to generate a build system appropriate to the user's machine.

Best Regards,
Ryan

**Comment by elfring** [comment]
Thanks for [your build script addition](https://github.com/rlguy/GridFluidSim3D/commit/adbdf4654783c8b11c2c3fbbbe2b1546b0f64150).
