### ISSUE TITLE
Vector subscript out of range when running the basic example

### ISSUE THREAD

**Issue by mingweiLIU** [rlguy/GridFluidSim3D#13]
I built the project with VS2015 x64, when running the basic example (image1) it crashed, error shows that the vector subscript out of range. I watched the stack it shows that the error is acurred by the function of what I showed in image2 and seems it caused by the variable buffer.pointDataH[0] since the size of the pointDataH is 0. I don't know how to fix it, could you help me?
![image](https://user-images.githubusercontent.com/11702952/31551076-11fdcbe8-b066-11e7-934e-78548b892fb3.png)
image1 code of basic example code
![image](https://user-images.githubusercontent.com/11702952/31551370-f00d16dc-b066-11e7-9f1b-21b8d291a0fc.png)
image2 error loaction

**Comment by wordwilly** [comment]
I met a similar problem. In my case, the program tries to assign "device global memory size" to an "unsigned long int" variable, but the memory size is too large. The range is 0 ~ 2^32 - 1, and the value is unfortunately 2^32. 

Function "int CLScalarField::_getMaxChunkLimit"
![image](https://user-images.githubusercontent.com/9249871/31935167-b0fb2d44-b8e0-11e7-9ddf-62b5f0e1b6ef.png)

**Comment by rlguy** [comment]
Thanks for these reports! I tested this on a machine with 8GB or device memory and was getting the same problem. The 'maxGlobalMem' variable would overflow to a negative value, which would later cause 'buffer.pointDataH' to be size zero.

I have changed the 'maxGlobalMem' and 'maxAlloc' variable to be the correct cl_ulong type. This should fix these errors.
