### ISSUE TITLE
The drop ball excample works not good

### ISSUE THREAD

**Issue by mingweiLIU** [rlguy/GridFluidSim3D#15]
Hi, I followed the "Hello World" excample about drop a ball of fluid in the center of the fluid simulation domain, however the 29.ply model is not same as the given one.
![image](https://user-images.githubusercontent.com/11702952/35555352-d6cba2ec-05d9-11e8-845c-2de56ac4770f.png)
(the model generated by my excample )
![image](https://user-images.githubusercontent.com/11702952/35555381-f1a2c0c8-05d9-11e8-893c-109c8db64576.png)
(the model in the readme example)
![image](https://user-images.githubusercontent.com/11702952/35555567-854437ee-05da-11e8-8231-774c8fb103b1.png)
(the code in my test)

**Comment by rlguy** [comment]
Hello mingweiLIU,

I am no longer maintaining this repository, but I'll try to figure out what is causing this error.

Would you be able to send me the 29.ply file? If you create a .zip of the file, you can attach it to your reply. And would you also attach the log file that is located in the 'logs' directory?

Also let me know your system specs:

**Operating System**
**CPU Model**
**Graphics Card/Chip Model**

Thanks!

**Comment by mingweiLIU** [comment]
Thanks a lot, my test enviroment is Windows10, Intel Xeon E5-2650 and NVIIDA Quadro M5000. Actually the excample finally worked after another build through the repository.
