### ISSUE TITLE
How to improve the efficiency of simulation for fluid on surface？

### ISSUE THREAD

**Issue by mingweiLIU** [rlguy/GridFluidSim3D#17]
Hi, I  am trying to simulating fluid on a surface with up and down hill, seems it is no need to initalize the simulation domain to be a box, it will be of more efficient to use the surface to initialize the buttom of the box, since it will decline the number of grid. Then how could we do that if it supported? 
![default](https://user-images.githubusercontent.com/11702952/43723235-bc452aea-99c9-11e8-8449-60368f59db7c.png)
(The above figure shows the case that the yellow box is the initalized simulation domain, while the black grids should not be used since the fluid is flow on the surface, if use the origal box, it will require more computation for the simulation, we should and how to decline the  initalized domain? )

**Comment by rlguy** [comment]
Hello,

The domain must be a box due to efficiency and simplicity of memory layout.

Note: This repository is no longer being maintained. This codebase has been further developed and has now become the [Blender FLIP Fluids](https://github.com/rlguy/Blender-FLIP-Fluids) project.

\- Ryan
