### ISSUE TITLE
issues with compilation

### ISSUE THREAD

**Issue by cyrstem** [rlguy/GridFluidSim3D#18]
hey  when trying to  make  i get this
`
Documents/GridFluidSim3D/build  master ✗                                                               850d ◒
▶ make
Scanning dependencies of target objects
[  2%] Building CXX object CMakeFiles/objects.dir/src/aabb.cpp.o
[  4%] Building CXX object CMakeFiles/objects.dir/src/anisotropicparticlemesher.cpp.o
[  6%] Building CXX object CMakeFiles/objects.dir/src/c_bindings/cbindings.cpp.o
[  9%] Building CXX object CMakeFiles/objects.dir/src/c_bindings/config_c.cpp.o
[ 11%] Building CXX object CMakeFiles/objects.dir/src/c_bindings/cuboidfluidsource_c.cpp.o
[ 13%] Building CXX object CMakeFiles/objects.dir/src/c_bindings/fluidsimulation_c.cpp.o
In file included from /home/jacos/Documents/GridFluidSim3D/src/c_bindings/../clscalarfield.h:37,
                 from /home/jacos/Documents/GridFluidSim3D/src/c_bindings/../fluidsimulation.h:32,
                 from /home/jacos/Documents/GridFluidSim3D/src/c_bindings/fluidsimulation_c.cpp:1:
/opt/cuda/include/CL/cl.hpp:5085:28: warning: ignoring attributes on template argument ‘cl_int’ {aka ‘int’} [-Wignored-attributes]
 5085 |         VECTOR_CLASS<cl_int>* binaryStatus = NULL,
      |                            ^
In file included from /home/jacos/Documents/GridFluidSim3D/src/c_bindings/../clscalarfield.h:56,
                 from /home/jacos/Documents/GridFluidSim3D/src/c_bindings/../fluidsimulation.h:32,
                 from /home/jacos/Documents/GridFluidSim3D/src/c_bindings/fluidsimulation_c.cpp:1:
/home/jacos/Documents/GridFluidSim3D/src/c_bindings/../arrayview3d.h: In member function ‘void ArrayView3d<T>::getViewAsArray3d(Array3d<T>&)’:
/home/jacos/Documents/GridFluidSim3D/src/c_bindings/../arrayview3d.h:192:16: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
  192 |         return view;
      |                ^~~~
make[2]: *** [CMakeFiles/objects.dir/build.make:128: CMakeFiles/objects.dir/src/c_bindings/fluidsimulation_c.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/objects.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by elch10** [comment]
@cyrstem I was able to build after change `src/arrayview3d.h:175`
```cpp
void getViewAsArray3d(Array3d<T> &view) {
```
to
```cpp
Array3d<T> getViewAsArray3d(Array3d<T> &view) {
```

**Comment by cyrstem** [comment]
that work thanks
